mpirun -n 1 ./oddeven 2
mpirun -n 1 ./oddeven 4
mpirun -n 1 ./oddeven 8
mpirun -n 1 ./oddeven 16
mpirun -n 2 ./oddeven 2
mpirun -n 2 ./oddeven 4
mpirun -n 2 ./oddeven 8
mpirun -n 2 ./oddeven 16
mpirun -n 4 ./oddeven 2
mpirun -n 4 ./oddeven 4
mpirun -n 4 ./oddeven 8
mpirun -n 4 ./oddeven 16
mpirun -n 8 ./oddeven 2
mpirun -n 8 ./oddeven 4
mpirun -n 8 ./oddeven 8
mpirun -n 8 ./oddeven 16
